### ISSUE TITLE
please provide training and testing set 

### ISSUE THREAD

**Issue by Moshiii** [beyondacm/Code2Que#1]
Hello,

Thanks for your awesome work! I am a researcher and I am trying to reproduce your work. I run main.py but I found it is missing dataset:
```
Traceback (most recent call last):
  File "main.py", line 623, in <module>
    run(existing_model_name)
  File "main.py", line 494, in run
    modules, consts, options = init_modules()
  File "main.py", line 120, in init_modules
    [_, dic, hfw, w2i, i2w, w2w] = pickle.load(open(cfg.cc.TRAINING_DATA_PATH + "dic.pkl", "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/d/code/Code2Que-master/source_code/deepmind/train_set/dic.pkl'
```

can you please provide training and testing data?

Thanks

**Comment by Moshiii** [comment]
I found it in the paper: https://zenodo.org/record/3816592
